export const accessToken =
  "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm5pY2tuYW1lIjoiYiIsImlhdCI6MTY4NDk1Njk4OCwiZXhwIjoxNjg0OTYwNTg4fQ.iSg-1baFQz-DaWzrWcmqFE6EgJlN1HiId1X20hDUf14";
// アクセストークンを表す文字列定数accessTokenをエクスポートしています。
